### ISSUE TITLE
Add compatibility to README or Documentation

### ISSUE THREAD

**Issue by jwkicklighter** [scroll-out/scroll-out#14]
Without browsing through all of the source, I'm not sure what browser compatibility looks like for the library. Does it work on IE9/10/11? etc. Would be really handy to have a list of minimum browsers on the home page to help know if it can be used.

**Comment by notoriousb1t** [comment]
Thank you for bringing that to my attention.  The intended compatibility is IE11, and modern mobile and desktop browsers.  The core features (using data attributes) should go back pretty far though.

The CSS Custom Properties are only available on some of those platforms, but the good news is that providing fallback properties allows older browsers to degrade gracefully.

As soon as I get a small block of time, I'll run it through cross browser testing and post a chart in the documentation and README. 😄

**Comment by notoriousb1t** [comment]
I have added a compat section in the README and in the docs: https://scroll-out.github.io/guide.html#compatibility

**Comment by jwkicklighter** [comment]
Thanks for working on this so quickly!
