### ISSUE TITLE
Elements are registering in when they should be out.

### ISSUE THREAD

**Issue by richardegil-love** [scroll-out/scroll-out#18]
I have this integrated with a Shopify theme, and some of the elements that I am targeting using a specific class are registering in the viewport when they are out of the viewport.

Any idea why?

**Comment by richardegil-love** [comment]
Also all the elements with the same class being used for a target are firing all at once.

**Comment by richardegil-love** [comment]
Unfortunately, I can publicly share the site. Is there any way for me to private message you?

**Comment by notoriousb1t** [comment]
I didn't get an email from you, but in troubleshooting #19, I realize this may be related.  Can you try upgrading to 2.2.3 and let me know if that works for you?

**Comment by richardegil-love** [comment]
Sorry about the delay. I message you right before I was out for the weekend. Let me try your suggestion and if that does not work I will shoot you an email.

Thanks!

**Comment by richardegil-love** [comment]
That seems to have fixed it!!! You are a lifesaver!

**Comment by notoriousb1t** [comment]
Great!
