### ISSUE TITLE
Position Relative doesn't get tracked correctly

### ISSUE THREAD

**Issue by LeeCampbellr** [scroll-out/scroll-out#19]
Having position: relative on a parent container causes the elements inside the container to not be tracked correctly. Unfortunately I'm not very good with JS so I haven't been able to narrow down why position relative causes this issue, I did put together a JSfiddle to showcase the issue I am having. 

[http://jsfiddle.net/n9fa0hxt/4/](JSFiddle)

**Comment by notoriousb1t** [comment]
I am able to reproduce this.  Currently it is calculating the distance from scrollTop by the offsetTop which does not work as I had intended when the parent is relative.  I am going to be able to look into this in the next couple of days.  Thank you for letting me know. 😄

**Comment by notoriousb1t** [comment]
I believe I have fixed this.  I made a change [here](https://github.com/scroll-out/scroll-out/commit/051589ad84f8332f94962a73ed5c58d3bf627131#diff-8cfead41d88ad47d44509a8ab0a109ad) and did some regression testing.  Try using version 2.2.3 and let me know if that works for you.

**Comment by LeeCampbellr** [comment]
This works great now! Thanks so much for looking into this and fixing the issue!

**Comment by notoriousb1t** [comment]
No problem at all 😀
