### ISSUE TITLE
Once I call the teardown method, scroll-out will never work even I init it again

### ISSUE THREAD

**Issue by McLemore** [scroll-out/scroll-out#23]
I write a nextjs project, and init scroll-out in one page's componentDidMount method and teardown in componentWillUnmount method. When I first visit the page, it works well, but the second time i visit this page, scroll-out not work any more. After i lookup the source code, i find that clearTask never be set to zero.

**Comment by notoriousb1t** [comment]
Ok, confirmed here: https://codepen.io/notoriousb1t/pen/5d3a22d31ac20a5a4dbf426949b19687

**Comment by notoriousb1t** [comment]
This has been fixed in version 2.2.4.  Please try this version and let me know 😄

**Comment by McLemore** [comment]
Thanks for your work. It works now.👍
