### ISSUE TITLE
How to use scroll-out in Angular 7?

### ISSUE THREAD

**Issue by seanghay** [scroll-out/scroll-out#25]
I found this library, and it's really interesting in term of size. I used the library with plain normal HTML, CSS, and JS, as a result, it works perfectly fine. However, it want to use it in my Angular 7 project, and it doesn't work. It seems like the library is not execute any code.
Here are my steps of adding this lib to the project.

## 1. Installation

```
npm i scroll-out
```

## 2. Import libs

```ts
.....
import ScrollOut from 'scroll-out'
import {AfterContentInit, Component, ElementRef, OnDestroy, OnInit} from '@angular/core';
.....
```

## 3. Add code to the MyComponent

```ts
import ScrollOut from 'scroll-out'
import {AfterViewInit, Component, ElementRef, OnDestroy, OnInit} from '@angular/core';

@Component({
  selector: 'app-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.scss'],
  animations: []
})
export class MyComponent implements OnInit, AfterContentInit, OnDestroy {
     data = [...];
      so: any;
     constructor(private el: ElementRef) {}
    
    ngAfterContentInit() {
        this.so = ScrollOut({
             scope: el.nativeElement
        });
    }
  
    ngOnInit() {

    }

    ngOnDestroy(): void {
        this.so.teardown();
    }
}
```

## 4. In my HTML `./detail.component.html`
```html
<ul>
   <li *ngFor="let item of data"  data-scroll>{{item.stuff}}</li>
</ul>
```

## 5. In my SCSS `'./detail.component.scss'`
```scss

[data-scroll] {
  transition: opacity 1s;
}
[data-scroll="in"] {
  opacity: 1;
}
[data-scroll="out"] {
  opacity: 0;
}

```

Finally, I did follow the guide in [Use with Frameworks](https://scroll-out.github.io/guide.html#angular)
>> If you have any sample project of `scroll-out` with @angular, please kindly share us.

**Comment by notoriousb1t** [comment]
I'm having issues getting codesandbox to work, so I can't pull up an example at this particular minute, but I think one of the issues is 
```ts
    ngAfterContentInit() {
        this.so = ScrollOut({
             scope: el.nativeElement
        });
    }
```
The line with scope should be ```this.el.nativeElement```.  Outside of that everything looks correct.  Are you getting any console errors?

**Comment by seanghay** [comment]
> I'm having issues getting codesandbox to work, so I can't pull up an example at this particular minute, but I think one of the issues is
> 
> ```ts
>     ngAfterContentInit() {
>         this.so = ScrollOut({
>              scope: el.nativeElement
>         });
>     }
> ```
> 
> The line with scope should be `this.el.nativeElement`. Outside of that everything looks correct. Are you getting any console errors?

Yes, I did add `this.el.nativeElement`, but still doesn't work

**Comment by seanghay** [comment]
@notoriousb1t I inspected in the Chrome, and I saw the attr `data-scroll` didn't change to anything. I think there's something wrong with scroll event.

**Comment by seanghay** [comment]
Here is my [StackBlitz](https://stackblitz.com/edit/angular-scroll-out) 
It doesn't work with `*ngFor="let item of data"`, and it works perfectly fine without it.

**Comment by notoriousb1t** [comment]
If you swap ngAfterContentInit with ngAfterViewInit it works.  It looks like the issue is that ngAfterContentInit is fired before ng templates are evaluated, so the *ngFor hasn't created the li's when ScrollOut is initialized. ngAfterViewInit appears to occur after the *ngFor has been evaluated.

**Comment by seanghay** [comment]
> If you swap ngAfterContentInit with ngAfterViewInit it works. It looks like the issue is that ngAfterContentInit is fired before ng templates are evaluated, so the *ngFor hasn't created the li's when ScrollOut is initialized. ngAfterViewInit appears to occur after the *ngFor has been evaluated.

Thanks! It works.

**Comment by seanghay** [comment]
> If you swap ngAfterContentInit with ngAfterViewInit it works. It looks like the issue is that ngAfterContentInit is fired before ng templates are evaluated, so the *ngFor hasn't created the li's when ScrollOut is initialized. ngAfterViewInit appears to occur after the *ngFor has been evaluated.

Thanks! It works.
