### ISSUE TITLE
where does [data-scroll="on"] goes to?

### ISSUE THREAD

**Issue by thwbn** [scroll-out/scroll-out#29]
Hi,

when I tried to reproduce the sticky-header example it did not work. Maybe because I am not able to split html CSS an JS correctly. Everything works as long as I exclude [data-scroll="on"]. Not as expected, but it worked. After all I head a look in to the scroll-out.js 

All I can find is the "in" and "out" but no "on" 
Where is my mistake?

Thanks a ton
Thorsten
![scroll-out-2019-01-08 17_02_57-window](https://user-images.githubusercontent.com/18221200/50843688-77910f80-1369-11e9-884c-3c560e2db53c.png)
![scroll-out-2__2019-01-08 17_19_36-window](https://user-images.githubusercontent.com/18221200/50843801-ac9d6200-1369-11e9-85fa-a5893d67e2c8.png)
![scroll-out-3__2019-01-08 17_19_36-window](https://user-images.githubusercontent.com/18221200/50843909-ec644980-1369-11e9-8a32-d7c44628b0de.png)

**Comment by notoriousb1t** [comment]
This as an error in the documentation. I have updated it to say "in" instead of "on".  Let me know if that works for you :smile:

**Comment by thwbn** [comment]
You are awesome!
Thank you very much! Thought I did not understood something.  

works now as expected.
Thorsten
