### ISSUE TITLE
data-scroll doesn't works on inline elements

### ISSUE THREAD

**Issue by fabioquarantini** [scroll-out/scroll-out#34]
When I add `data-scroll` to a inline element the value is always `out`.

**Comment by notoriousb1t** [comment]
Can you provide an example in CodePen or another playground?  Also, does this work for you when you set the display to inline-block?

**Comment by fabioquarantini** [comment]
Yes with the inline-block it works. Here the example:
https://codepen.io/febba/pen/VgXNGv

**Comment by notoriousb1t** [comment]
I think I have narrowed down the issue. It appears that elements don't have a clientHeight or clientWidth when set to inline.  getComputedStyle just shows up as "auto" which isn't very helpful in determining the height.  I will try adding a fallback to offsetHeight and offsetWidth (which ought to be populated even for an inline element) and run some tests tonight.

**Comment by notoriousb1t** [comment]
Okay, this has been patched in 2.2.7.  Let me know if that works for you.  Also, thanks for taking the time to report this and provide an example. 😄

**Comment by fabioquarantini** [comment]
Thanks. Works like a charm!
