### ISSUE TITLE
Scroll-out and Smooth-scrollbar compatibility

### ISSUE THREAD

**Issue by fabioquarantini** [scroll-out/scroll-out#35]
I tried to use Scroll-out with [smooth-scrollbar](https://idiotwu.github.io/smooth-scrollbar/) but it does not seem to work (even with `scrollingElement`). Any idea?
Example: [https://codepen.io/febba/pen/jdJgaa](https://codepen.io/febba/pen/jdJgaa)

**Comment by notoriousb1t** [comment]
Smooth Scrollbar uses translate to move a pane in and out of view so it isn't technically scrolling.  Let me noodle on this for a bit to see if there is a way to wire these together.

**Comment by notoriousb1t** [comment]
Sorry for letting this sit so long. As much as I want to support this, I don't think these two libraries can work together because smooth-scrollbar isn't using native scrolling.
