### ISSUE TITLE
Configuration using data attributes

### ISSUE THREAD

**Issue by rawksteady** [scroll-out/scroll-out#38]
First off: Thank you for this! Really easy to get setup and works wonders!

I'm under the impression that most of the setup can be done using data attributes. Such as `<div data-scroll data-scroll-once="true" data-scroll-threshold="0.9">`.

If it's already supposed to work, could you point me in the right direction? If not, could it be added?

Again, thank you for the fine work!

**Comment by notoriousb1t** [comment]
It does not currently work that way, but I really like the idea! :smile: 

Looking at the configuration, I think the following options could have their configuration detected off of the element if I rearranged the internals somewhat:

- data-scroll-once
- data-scroll-threshold
- data-scroll-element (a selector for scrollingElement)
- data-offset
- data-css-props (comma delimited list)

The ScrollOut() function could supply defaults, and the data attributes could override that.

How does that sound?

**Comment by rawksteady** [comment]
The way you describe it is how I initially thought it worked so I say go for it!

**Comment by notoriousb1t** [comment]
This type of rewrite isn't going to happen soon. (Only have so much time for new features). I'm going to close this for now. If my schedule frees up at some point, I will revisit it. Also if anyone feels motivated to build it out, I will happily accept a PR (as long as it doesn't balloon the size of the library)
