### ISSUE TITLE
Why clamp the viewportY value for parallax?

### ISSUE THREAD

**Issue by Djules** [scroll-out/scroll-out#39]
I can see through the doc and the code that viewportX/Y values are clamped but when doing parallax, I want to see object moving while their center position isn't yet in the viewport (so value can be greater or lesser than 1/-1).

Maybe you can give possibility to clamp or not values with an option?

**Comment by notoriousb1t** [comment]
This was originally added because I didn't think it would be relevant to update a css var out of view.

I am open to adding this option. I think perhaps this could be added as an option to the cssProps configuration. For example:

```js
ScrollOut({
  cssProps: {
    viewportY: {
      minValue: 2,
      maxValue: 2
    } 
  }
})
```
What do you think?

**Comment by notoriousb1t** [comment]
Closing this as stale
