### ISSUE TITLE
Issue with Vue Framework

### ISSUE THREAD

**Issue by yudyananda** [scroll-out/scroll-out#43]
This is script structure in my HTML

```html
<div class="foo" data-scroll></div>
<script src="vue.js"></script>
<script src="scroll-out.js"></script>
<script>
ScrollOut({
  /* options */
});

// some vue app script
new Vue({
	  el:'#app',
	  components: { 'mobile-nav' : mobileNav },
	  // menu nav
	  data: {
	  	showNav: false,
	  }
  })
<script>
```
Refresh my browser but still nothing happen to data-scroll attibute.  Any Idea?

I read the [guide](https://scroll-out.github.io/guide.html#use-with-frameworks) about how to using it with framework, but i have no idea where exactly to put the script

thanks

**Comment by notoriousb1t** [comment]
I think ScrollOut should probably be in the mounted() function of the Vue instance. 

I think that the ScrollOut is being loaded before the elements exist (and it has no reason to index the DOM after the Vue instance is initialized.

**Comment by yudyananda** [comment]
noted, thanks for led me to the right path

**Comment by merijnponzo** [comment]
Hello,
I followed the Use with Frameworks part but i still need help to get the data-scroll element working.

Within script
```
import ScrollOut from 'scroll-out'
```
Within mounted()
```
 this.so = ScrollOut({
      scope: this.$el
    })
```
Within my vue template
```
<div data-scroll>hello</div>
```
but nothing happens 

Can u help me?

**Comment by merijnponzo** [comment]
It was late.
```
this.so = ScrollOut({
      scope: this.$el
    })
    ScrollOut({
      targets: '.header',
      offset: 400
    })
```
