### ISSUE TITLE
More animation css codes please

### ISSUE THREAD

**Issue by bsde1234** [scroll-out/scroll-out#44]
I get slideinup animation with following code as you described in your demo.
```
.scroll {
  opacity: 0;
  will-change: transform, scale, opacity;
  transform: translateY(6rem) scale(0.93);
  transition: all 1.5s cubic-bezier(0.165, 0.84, 0.44, 1);
}
.scroll[data-scroll="in"] {
  opacity: 1;
  transform: translateY(0) scale(1);
}
```
```
ScrollOut({
targets: '.scroll'
});
```
I would like to have more css codes for animation. Can you point me to some css codes for animations like bounce, fade, flip, rotate, zoom etc

**Comment by bsde1234** [comment]
I created a question in stackoverflow [here](https://stackoverflow.com/questions/58179953/animate-on-scroll-blinking-in-mobile-chrome)

**Comment by notoriousb1t** [comment]
I recommend checking out https://daneden.github.io/animate.css/ for more animations. I have a section in the docs for using the two together: https://scroll-out.github.io/guide.html#use-it-with-animate-css

**Comment by bsde1234** [comment]
@notoriousb1t thanks for the suggestion. But I dont want to use animate.css combination because website is not smooth. When I use custom css provided by you it works beautifully.

**Comment by notoriousb1t** [comment]
I'm afraid animate.css is probably your best bet for easy material. I don't think I want to build out another animation library outside of the ones I have. I would recommend that if you want to learn more about web animation and be able to create smooth animations, join http://animationatwork.slack.com/ and ask questions and pay attention to what all the smart people there have to say. 😄
