### ISSUE TITLE
How to add ScrollOut js to Nuxtjs

### ISSUE THREAD

**Issue by saadkhaan** [scroll-out/scroll-out#47]
I need your help to add scrollOut js in Nuxt js project. I am getting window not defined error.

I have followed Nuxt's guidlines of adding a plugin like
`if (process.client) {
  require('external_library')
}`
However this isn't working for me even after adding the plugin in the nuxt.config.js file
```

import ScrollOut from "scroll-out";

export default {
  methods: {
    textAnim() {
      TweenMax.set("#logo, .hidetext, #about-text", { visibility: 'visible' })
      const tl = new TimelineMax();
        tl.from("#logo path", 1, { stroke: "white", drawSVG: "0" });
        tl.to("#s_1_", .5, { fill: "white", stroke: "none" }, "-=.3")
        tl.to("#k_1_", .5, { fill: "gray", stroke: "none"}, "-=.3")
        tl.staggerFrom(".hidetext", 1, { y: "130%", ease: Power4.easeOut }, 0.5);
        tl.from("#about-text", 0.5, { alpha: 0, y: 50, ease: Power1.easeOut }, "-=.5");
    }
  },
  mounted() {
    ScrollOut({
      targets: "h3, [data-splitting], ul li",
      threshold: .5
    });
    this.textAnim();
  },
  components: {
    Logo
  }
};
```
Also in my package.json file I see` "nuxt": "^2.0.0",` version. I created the project using `create-nuxt-app`.

Any help is really appreciated.

Thanking you

**Comment by notoriousb1t** [comment]
Try v2.2.8 and let me know if that works. I removed the global declarations so that importing it doesn't attempt to access window. I believe this should fix the situation with Nuxt.

**Comment by saadkhaan** [comment]
> 
> 
> Try v2.2.8 and let me know if that works. I removed the global declarations so that importing it doesn't attempt to access window. I believe this should fix the situation with Nuxt.

Working now, thank you
