### ISSUE TITLE
Limited functionality in Edge

### ISSUE THREAD

**Issue by wfendler** [scroll-out/scroll-out#50]
I don't think this is as much an issue with scroll-out as it is with Edge's lack of (or limited) support of `var()` inside `calc()` but since this is one of, if not _the_, primary use case for the library and most of the demos are broken in Edge I thought I'd share some notes.

- The main problem is documented pretty well in this [post on Codepen](https://codepen.io/danwilson/details/zwqvOK)
- Opacity is the only property that changes in the [Scaling Gallery on Scroll demo](https://codepen.io/notoriousb1t/pen/GGXgbP)
- All demos using [Splitting.js](https://splitting.js.org/) are either broken or partially functioning too since these often use `var()` and `calc()` to calculate a delay based on a character's position in the string.
- It seems that using the variables on their own (without `calc`) is the only way they work in Edge (even when using calc in locations that don't need a unit like `opacity` and `transform: scale();`)

Can you confirm this is a limitation of Edge instead of something being broken in the library?

If it is an Edge limitation,

1. Are there ways you recommend working around it to get the intended behavior of rules like: `transform: rotateX(calc(180deg * var(--visible-y)));`?
2. It would be helpful to have a note about these "gotchas" on the [Compatibility section](https://scroll-out.github.io/guide.html#compatibility) in the docs. Although technically true, the "ScrollOut is compatible with all modern browsers and Internet Explorer." line could be misleading.

Thanks for any help!

Edit: I haven't tried this yet so I'm not certain it's as bullet-proof as I'm guessing it will be. It seems the obvious answer to this is to switch from using the provided CSS variables for animation to the event handlers in javascript to animate elements directly or have them set a `:root` variable that has already done whatever `calc()` is currently handling in CSS since this is the one scenario that Edge seems to be able to handle.

**Comment by notoriousb1t** [comment]
This is a limitation of Edge. Rather than just writing it off, I am inclined to think that we can soften this a little by adding a feature. Some thoughts:

### Allow the user to provide a unit instead of true for all css properties*
```ts
ScrollOut({
  cssProps: 'px'
})

ScrollOut({
  cssProps: {
     visibleY: '%'
  }
})
```

### Allow the user provide a function to calculate the final value with a return type of string*
```ts
ScrollOut({
  cssProps: {
     visibleY: (value) => `${value}px`
  }
})
```

Adding one or both of these features and then adding a section about improving compatibility with Edge should do the trick.  The good news is that if we do nothing, the CSS can still be written in a way that progressively enhances. The scrolling gallery for example, still functions well in Edge even if it isn't nearly as polished. If we do nothing, we need to add to the documentation about Edge issues.

@shshaw can you also weigh in on this?

**Comment by shshaw** [comment]
The core "scroll detection" functionality should definitely work in nearly every browser with the `data-` attributes. The CSS Variables should be treated as a progressive enhancement, working with standards compatible browsers.

With the recent switch to Blink engine (Chromium / Chrome) under the hood, the latest version of Edge should support all of the features without any changes. Edge is supposed to be "evergreen" so folks who are still on Edge 15 are there by choice and can't expect the latest & greatest.

If there is time to add an enhancement, I'd lean toward the function approach as that will give the most flexibility and will solve more than just Edge compatibility. That function could receive both pixel and percentage values and maybe even the element to let the user do additional calculations for those variables. Overall, that shouldn't add much weight to the library either.

**Comment by notoriousb1t** [comment]
I added a blurb in the documentation https://github.com/scroll-out/scroll-out.github.io/commit/643b0cfbb931e27f28c7eaafc53ca603131be092

I think that is probably sufficient to not the issue. I think I will punt on the enhancement unless we get a ton more bugs filed for this.
