### ISSUE TITLE
Vue Directive

### ISSUE THREAD

**Issue by nam-co** [scroll-out/scroll-out#52]
Hi, thanks for the great package, I was wondering if its possible to create a Vue-directive (v-scrolout) instead of having to do a mounted function for every element in the page
```
   mounted: function() {
      ScrollOut({
         scrollingElement: ".flow",
         targets: ".item_img"
      });
   }
```
for example I tried this but it doesn't work

```
Vue.directive('scrollout', 
    function(el) {
      ScrollOut({
         scrollingElement: ".flow",
         targets: el._prevClass
      });
    }
);
```
Appreciate any help, thanks

**Comment by notoriousb1t** [comment]
Try something like this:

```ts
Vue.directive('scrollout', {
  bind(el) {
    el.scrollout_ = ScrollOut({
       scrollingElement: ".flow",
       targets: el
    });
  },
  update(el) {
    if (el.scrollout_) {
      el.scrollout_.update();
    }
  },
  unbind(el) {
    if (el.scrollout_) {
       el.scrollout_.teardown();
       delete el.scrollout_
    }
  }
})
```

I don't have a working example readily available, but I believe something like that should work.

**Comment by nam-co** [comment]
Thanks @notoriousb1t , I will try it, thank for the work

**Comment by notoriousb1t** [comment]
Did that work for you?

**Comment by notoriousb1t** [comment]
Working on a similar issue in #55 Working demo here: https://codepen.io/notoriousb1t/pen/eYpXJdR.
