### ISSUE TITLE
Directional Awareness

### ISSUE THREAD

**Issue by notoriousb1t** [scroll-out/scroll-out#6]
It would be helpful in addition to in and out to provide a data attribute that indicates which direction the scroll is going, something like;

```html
// when scrolling down
<div data-scroll="in" data-direction="to-end"></div>

// when scrolling up
<div data-scroll="in" data-direction="to-start"></div>
```

This would aid in making CSS effects that act differently when scrolling up vs down while the element is in view.

Thoughts @shshaw ?

**Comment by notoriousb1t** [comment]
Tracking changes here: https://github.com/scroll-out/scroll-out/tree/directional-awareness

**Comment by shshaw** [comment]
Excellent! Seems to be working correctly.

Might want to trigger the scroll update upon init so that it fires the callbacks right away with visible/not visible, etc. Maybe pass a property on the context so the callback can know if it's the initial call or not.

**Comment by shshaw** [comment]
I'm on board with the grouping of everything. 1.7 is nothing for the amount of functionality provided.

**Comment by notoriousb1t** [comment]
2.0.1 is published and I have a little demo worked up for the visibility-y variable:

https://codepen.io/notoriousb1t/pen/GGXgbP

**Comment by shshaw** [comment]
Tweaked the demo params a little bit. This might showcase it a little more apparently: https://codepen.io/shshaw/pen/OEoYeV

**Comment by notoriousb1t** [comment]
Ok, I  incorporated those changes into the pen 😄
